version: '3.4'

services:
  
  redis_cache:
    image: redis:6.2.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    networks:
      - net1

  weather-api:
    image: weather-api-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.7"
        NODE_VERSION: "none"
    depends_on:
      - redis_cache
    volumes:
      - ..:/weather_api
    user: vscode
    command: sleep infinity
    ports:
      - "8000:8000"
    networks:
      - net1

volumes:
  redis_data: null

networks:
  net1: null
